## Copyright © 2020, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

    title: "Create compute instance and an Autonomous Transaction Processing (ATP) database in Oracle Cloud Infrastructure"
    stackDescription: "This code will help you deploy a compute instance and an Autonomous Transaction Processing (ATP) database in Oracle Cloud Infrastructure."
    schemaVersion: 1.1.0
    version: "20190404"
    locale: "en"

    variableGroups:
    - title: General Configuration
      visible: false
      variables:
      - tenancy_ocid

    - title: Required Configuration
      visible: true  
      variables:
      - autonomous_database_admin_password
      - compartment_ocid
      - region

    - title: Optional Configuration
      visible: true
      variables:      
      - ad_number
      - ad_name
      - instance_os
      - linux_os_version
      - instance_shape
      - volume_display_name
      - volume_size_in_gbs
      - volume_count
      - volume_attachment_type
      - autonomous_database_cpu_core_count
      - autonomous_database_db_name
      - autonomous_database_display_name
      - autonomous_database_is_auto_scaling_enabled
      - autonomous_database_data_storage_size_in_tbs
      - autonomous_database_db_workload
      - autonomous_database_license_model

    
    variables:

      compartment_ocid:
        type: oci:identity:compartment:id
        required: true
        visibile: true
        title: Compartment
        description: "Compartment where you want to create the solution resources"

      region:
        type: oci:identity:region:name
        required: true
        visibile: true
        title: Region
        description: "Region where you want to deploy the resources defined by this stack."

      autonomous_database_admin_password:
        type: password
        required: true
        title: "Autonomous database Admin password"
        description: "Autonomous database Admin password."

      # Optional Configuration
      ad_number: 
        type: number
        required: false
        default: 0
        description: "Which availability domain to deploy to depending on quota, zero based."
      
      ad_name: 
        type: oci:identity:availabilitydomain:name
        required: false
        description: "Which Availability domain name to deploy."

      instance_os: 
        type: string
        required: false
        default: "Oracle Linux"
        description: "Operating system for compute instances."

      linux_os_version:
        type: string
        required: false
        default: "7.8"
        description: "Operating system version for all Linux instances."

      instance_shape:
        type: string
        required: false
        default: "VM.Standard2.4"
        description: "Instance Shape."

      volume_display_name:
        type: string
        required: false
        default: "AppVolume1"
        description: "Instance volume display name."

      volume_size_in_gbs:
        type: string
        required: false
        default: "100"
        description: "Instance volume size in gigabytes."

      volume_count:
        type: number
        required: false
        default: 1
        description: "Instance volume count" 

      volume_attachment_type:
        type: string
        required: false
        default: "paravirtualized"
        description: "Instance volume attachment type."
      
      autonomous_database_cpu_core_count:
        type: string
        required: false
        default: "4"
        description: "Autonomous database CPU core count."

      autonomous_database_db_name:
        type: string
        required: false
        default: "aTFdb"
        description: "Autonomous database CPU core count."

      autonomous_database_display_name:
        type: string
        required: false
        default: "My ATP DB"
        description: "Autonomous database display name."

      autonomous_database_is_auto_scaling_enabled:
        type: string
        required: false
        default: "false"
        description: "Autonomous database auto-scaling enabled."

      autonomous_database_data_storage_size_in_tbs:
        type: string
        required: false
        default: "1"
        description: "Autonomous database data storage size in terabytes."  

      autonomous_database_db_workload:
        type: string
        required: false
        default: "OLTP"
        description: "Autonomous database DB workload."      

      autonomous_database_license_model:
        type: string
        required: false
        default: "BRING_YOUR_OWN_LICENSE"
        description: "Autonomous database License Model." 

      autonomous_database_data_safe_status:
        type: string
        required: false
        default: "NOT_REGISTERED"
        description: "Autonomous database DataSafe Status" 

    outputs:
      generated_ssh_private_key:
        title: "Generated SSH Private Key"
        displayText: "Generated SSH Private Key"
        type: string
        visible: true
